package com.prudhvir3ddy.rideshare.utils

object Constants {
  const val TRIP_PATH = "tripPath"
  const val REQUEST_CAB = "requestCab"
  const val PICK_UP_LAT = "pickUpLat"
  const val PICK_UP_LNG = "pickUpLng"
  const val DROP_LAT = "dropLat"
  const val DROP_LNG = "dropLng"
  const val CAB_BOOKED = "cabBooked"
  const val PICK_UP_PATH = "pickUpPath"
  const val TYPE = "type"
  const val NEAR_BY_CABS = "nearByCabs"
  const val LOCATIONS = "locations"
  const val LOCATION = "location"
  const val CAB_IS_ARRIVING = "cabIsArriving"
  const val CAB_ARRIVED = "cabArrived"
  const val LAT = "lat"
  const val LNG = "lng"
  const val TRIP_START = "tripStart"
  const val TRIP_END = "tripEnd"
  const val ROUTES_NOT_AVAILABLE = "routesNotAvailable"
  const val DIRECTION_API_FAILED = "directionApiFailed"
  const val ERROR = "error"
}